[git]
conventional_commits = true
filter_unconventional = true
split_commits = true
sort_commits = "newest"
tag_pattern = "^v\\d+\\.\\d+\\.\\d+$"

[[git.commit_parsers]]
message = "^BREAKING"
group = "<!-- 0 -->⚠️ Breaking"
breaking = true

[[git.commit_parsers]]
message = "^feat"
group = "<!-- 1 -->✨ Added"

[[git.commit_parsers]]
message = "^fix"
group = "<!-- 2 -->🐛 Fixed"

[[git.commit_parsers]]
message = "^docs"
group = "<!-- 3 -->🔄 Changed"

[[git.commit_parsers]]
message = "^refactor"
group = "<!-- 3 -->🔄 Changed"

[[git.commit_parsers]]
message = "^perf"
group = "<!-- 3 -->🔄 Changed"

[[git.commit_parsers]]
message = "^deprecation"
group = "<!-- 3 -->🔄 Changed"

[[git.commit_parsers]]
message = "^test"
skip = true

[[git.commit_parsers]]
message = "^style"
skip = true

[[git.commit_parsers]]
message = "^chore"
skip = true

[bump]
breaking_always_bump_major = true
features_always_bump_minor = true
initial_tag = "v0.1.0"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""

body = """
{%- macro render_commit(commit) -%}
{%- set lines = commit.raw_message | split(pat="\n") -%}
{%- for line in lines -%}
{%- set trimmed = line | trim | replace(from="*", to="\\*") -%}
{%- if trimmed != "" -%}

{%- if trimmed | find_regex(pat="^!- ") | length > 0 -%}
- {{ trimmed
  | replace_regex(from="^!-\\s*", to="")
  | replace_regex(from="^[^\\s]+\\s+", to="")
}}

{%- elif trimmed | find_regex(pat="^- ") | length > 0 -%}
{{ trimmed | replace_regex(from="^-\\s*", to="  - ") }}

{%- elif loop.first -%}
- {%- if commit.scope %} _({{ commit.scope | replace(from="_", to="\\_") }})_ {% endif -%}{{ trimmed
  | replace_regex(from="^[^(]+\\([^)]*\\):\\s*", to="")
  | replace_regex(from="^[^\\s]+\\s+", to="")
}}

{%- endif %}

{%- endif -%}
{%- endfor -%}
{%- endmacro -%}

{%- if version %}
## {{ version | replace(from="v", to="") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else %}
## Unreleased
{%- endif %}

{%- for group, commits_in_group in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{%- for commit in commits_in_group %}
{{ self::render_commit(commit=commit) }}
{%- endfor %}

{%- endfor %}
"""
footer = """

<!-- generated by git-cliff -->
"""

trim = true
